//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dunfoss.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dunfoss.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информационные письма.
        /// </summary>
        public static string AcchiveLetters {
            get {
                return ResourceManager.GetString("AcchiveLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На согласовании.
        /// </summary>
        public static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество штук.
        /// </summary>
        public static string Am {
            get {
                return ResourceManager.GetString("Am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Собрания группы БТП.
        /// </summary>
        public static string ArchivePresentations {
            get {
                return ResourceManager.GetString("ArchivePresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средняя оценка.
        /// </summary>
        public static string AvgRange {
            get {
                return ResourceManager.GetString("AvgRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средняя оценка дизайнеров.
        /// </summary>
        public static string AvgRangeDes {
            get {
                return ResourceManager.GetString("AvgRangeDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться в меню.
        /// </summary>
        public static string BackMenu {
            get {
                return ResourceManager.GetString("BackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчеты БТП по дивизионам.
        /// </summary>
        public static string CalcDivGraph {
            get {
                return ResourceManager.GetString("CalcDivGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причины корректировок.
        /// </summary>
        public static string CausesGraph {
            get {
                return ResourceManager.GetString("CausesGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Центр.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3Д Дизайн. Показатели скорости закрытия задач.
        /// </summary>
        public static string ClosingTasks {
            get {
                return ResourceManager.GetString("ClosingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показатели скорости закрытия задач по офисам.
        /// </summary>
        public static string ClosureByOffice {
            get {
                return ResourceManager.GetString("ClosureByOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показатели скорости закрытия задач по неделям.
        /// </summary>
        public static string ClosureByWeek {
            get {
                return ResourceManager.GetString("ClosureByWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код RO.
        /// </summary>
        public static string CodeRo {
            get {
                return ResourceManager.GetString("CodeRo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код RU.
        /// </summary>
        public static string CodeRu {
            get {
                return ResourceManager.GetString("CodeRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корректировки расчетов БТП.
        /// </summary>
        public static string CorrectGraph {
            get {
                return ResourceManager.GetString("CorrectGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Построить.
        /// </summary>
        public static string CreateBtn {
            get {
                return ResourceManager.GetString("CreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Построение графиков.
        /// </summary>
        public static string CreateGraph {
            get {
                return ResourceManager.GetString("CreateGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция построения графиков.
        /// </summary>
        public static string CreateGraphBtn {
            get {
                return ResourceManager.GetString("CreateGraphBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Построение информационных писем.
        /// </summary>
        public static string CreateLetter {
            get {
                return ResourceManager.GetString("CreateLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подготовить презентацию к собранию.
        /// </summary>
        public static string CreatePresentation {
            get {
                return ResourceManager.GetString("CreatePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущие документы.
        /// </summary>
        public static string CurrentFiles {
            get {
                return ResourceManager.GetString("CurrentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата проведения.
        /// </summary>
        public static string DateMeeting {
            get {
                return ResourceManager.GetString("DateMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата проведения собрания.
        /// </summary>
        public static string DateSobr {
            get {
                return ResourceManager.GetString("DateSobr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3Д дизайнер.
        /// </summary>
        public static string DDesign {
            get {
                return ResourceManager.GetString("DDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просроченные задачи.
        /// </summary>
        public static string DelayedTasks {
            get {
                return ResourceManager.GetString("DelayedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дизайнер.
        /// </summary>
        public static string Designer {
            get {
                return ResourceManager.GetString("Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В процессе дизайна.
        /// </summary>
        public static string DesProc {
            get {
                return ResourceManager.GetString("DesProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дивизионы.
        /// </summary>
        public static string Divisions {
            get {
                return ResourceManager.GetString("Divisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчетчик.
        /// </summary>
        public static string Engineer {
            get {
                return ResourceManager.GetString("Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дальний Восток.
        /// </summary>
        public static string FEast {
            get {
                return ResourceManager.GetString("FEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтрация.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтрация по месяцам.
        /// </summary>
        public static string FilterMonth {
            get {
                return ResourceManager.GetString("FilterMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтрация по неделям.
        /// </summary>
        public static string FilterWeek {
            get {
                return ResourceManager.GetString("FilterWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти к отчету.
        /// </summary>
        public static string GoPresBtn {
            get {
                return ResourceManager.GetString("GoPresBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показатели по расчетам.
        /// </summary>
        public static string HasteCalc {
            get {
                return ResourceManager.GetString("HasteCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показатели по заказам.
        /// </summary>
        public static string HasteOrders {
            get {
                return ResourceManager.GetString("HasteOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая информация о загрузке.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть загрузку группы БТП.
        /// </summary>
        public static string kek {
            get {
                return ResourceManager.GetString("kek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество контуров, шт.
        /// </summary>
        public static string KolvoKonturov {
            get {
                return ResourceManager.GetString("KolvoKonturov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ссылка в црм / на диск G.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить.
        /// </summary>
        public static string LoadBtn {
            get {
                return ResourceManager.GetString("LoadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить файлы.
        /// </summary>
        public static string LoadFiles {
            get {
                return ResourceManager.GetString("LoadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход в личный кабинет.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Апрель.
        /// </summary>
        public static string MApr {
            get {
                return ResourceManager.GetString("MApr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Август.
        /// </summary>
        public static string MAug {
            get {
                return ResourceManager.GetString("MAug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Декабрь.
        /// </summary>
        public static string MDec {
            get {
                return ResourceManager.GetString("MDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Февраль.
        /// </summary>
        public static string MFeb {
            get {
                return ResourceManager.GetString("MFeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Январь.
        /// </summary>
        public static string MJan {
            get {
                return ResourceManager.GetString("MJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июль.
        /// </summary>
        public static string MJul {
            get {
                return ResourceManager.GetString("MJul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июнь.
        /// </summary>
        public static string MJun {
            get {
                return ResourceManager.GetString("MJun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Март.
        /// </summary>
        public static string MMar {
            get {
                return ResourceManager.GetString("MMar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Май.
        /// </summary>
        public static string MMay {
            get {
                return ResourceManager.GetString("MMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ноябрь.
        /// </summary>
        public static string MNov {
            get {
                return ResourceManager.GetString("MNov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Месяц.
        /// </summary>
        public static string Mnth {
            get {
                return ResourceManager.GetString("Mnth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Октябрь.
        /// </summary>
        public static string MOkt {
            get {
                return ResourceManager.GetString("MOkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По месяцам.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер месяца.
        /// </summary>
        public static string MonthNumber {
            get {
                return ResourceManager.GetString("MonthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Москва.
        /// </summary>
        public static string Moscow {
            get {
                return ResourceManager.GetString("Moscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сентябрь.
        /// </summary>
        public static string MSep {
            get {
                return ResourceManager.GetString("MSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новые расчеты БТП.
        /// </summary>
        public static string NewCalcGraph {
            get {
                return ResourceManager.GetString("NewCalcGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новые расчеты и корректировки БТП.
        /// </summary>
        public static string NewCorrGraph {
            get {
                return ResourceManager.GetString("NewCorrGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новости.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данных по заданному фильтру нет.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не просроченные задачи.
        /// </summary>
        public static string NormTasks {
            get {
                return ResourceManager.GetString("NormTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Северо-Запад.
        /// </summary>
        public static string Northwest {
            get {
                return ResourceManager.GetString("Northwest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объект(название).
        /// </summary>
        public static string Obj {
            get {
                return ResourceManager.GetString("Obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Офис.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказы БТП.
        /// </summary>
        public static string OrdersGraph {
            get {
                return ResourceManager.GetString("OrdersGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Важные документы.
        /// </summary>
        public static string OtherDocs {
            get {
                return ResourceManager.GetString("OtherDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество КП в задаче.
        /// </summary>
        public static string PiecesOfCalc {
            get {
                return ResourceManager.GetString("PiecesOfCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Офис продаж.
        /// </summary>
        public static string PlaceSale {
            get {
                return ResourceManager.GetString("PlaceSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причины корректировок.
        /// </summary>
        public static string PrichiniKorr {
            get {
                return ResourceManager.GetString("PrichiniKorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По кол-ву кодовых номеров.
        /// </summary>
        public static string QCode {
            get {
                return ResourceManager.GetString("QCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По кол-ву задач.
        /// </summary>
        public static string QTasks {
            get {
                return ResourceManager.GetString("QTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество расчетов.
        /// </summary>
        public static string QuantityCalc {
            get {
                return ResourceManager.GetString("QuantityCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество кодовых номеров.
        /// </summary>
        public static string QuantityCodeNumbers {
            get {
                return ResourceManager.GetString("QuantityCodeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во просроченных задач.
        /// </summary>
        public static string QuantityDelayedTasks {
            get {
                return ResourceManager.GetString("QuantityDelayedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество единичных расчетов в задачах.
        /// </summary>
        public static string QuantitySingleCals {
            get {
                return ResourceManager.GetString("QuantitySingleCals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество задач.
        /// </summary>
        public static string QuantityTasks {
            get {
                return ResourceManager.GetString("QuantityTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В очереди.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3Д Дизайн. Оценки по дизайнерам и Средняя скорость выполнения модели.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценки по дизайнерам.
        /// </summary>
        public static string RatingDes {
            get {
                return ResourceManager.GetString("RatingDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причины.
        /// </summary>
        public static string Reasons {
            get {
                return ResourceManager.GetString("Reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причины просроченных задач.
        /// </summary>
        public static string ReasonsGraph {
            get {
                return ResourceManager.GetString("ReasonsGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Презентация к собранию группы БТП. Период.
        /// </summary>
        public static string ReportTitle {
            get {
                return ResourceManager.GetString("ReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск по кодовому номеру модели.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти.
        /// </summary>
        public static string SearchBtn {
            get {
                return ResourceManager.GetString("SearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать все.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Российский портал группы БТП.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юг.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показатели скорости закрытия задач по неделям(O, P, S).
        /// </summary>
        public static string SpeedClosure {
            get {
                return ResourceManager.GetString("SpeedClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средняя скорость выполнения модели.
        /// </summary>
        public static string SpeedDes {
            get {
                return ResourceManager.GetString("SpeedDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость закрытия задач по расчетчикам.
        /// </summary>
        public static string SpeedGraph {
            get {
                return ResourceManager.GetString("SpeedGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика по задачам группы БТП.
        /// </summary>
        public static string StatisticsLink {
            get {
                return ResourceManager.GetString("StatisticsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Узнать статус выполнения задачи в CRM.
        /// </summary>
        public static string StatusLink {
            get {
                return ResourceManager.GetString("StatusLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица для 3Д дизайна.
        /// </summary>
        public static string Table3d {
            get {
                return ResourceManager.GetString("Table3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список телефонов сотрудников группы БТП.
        /// </summary>
        public static string TelephoneList {
            get {
                return ResourceManager.GetString("TelephoneList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип графика.
        /// </summary>
        public static string TypeGraph {
            get {
                return ResourceManager.GetString("TypeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружена на завод.
        /// </summary>
        public static string UpFac {
            get {
                return ResourceManager.GetString("UpFac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Урал.
        /// </summary>
        public static string Ural {
            get {
                return ResourceManager.GetString("Ural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посмотреть загрузку группы БТП.
        /// </summary>
        public static string ViewGroupLink {
            get {
                return ResourceManager.GetString("ViewGroupLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поволжье.
        /// </summary>
        public static string Volga {
            get {
                return ResourceManager.GetString("Volga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По неделям.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер недели.
        /// </summary>
        public static string WeekNumber {
            get {
                return ResourceManager.GetString("WeekNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неделя.
        /// </summary>
        public static string WeekSingle {
            get {
                return ResourceManager.GetString("WeekSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Западная Сибирь.
        /// </summary>
        public static string WestSib {
            get {
                return ResourceManager.GetString("WestSib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С дивизионами.
        /// </summary>
        public static string WithDiv {
            get {
                return ResourceManager.GetString("WithDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без дивизионов.
        /// </summary>
        public static string WithoutDiv {
            get {
                return ResourceManager.GetString("WithoutDiv", resourceCulture);
            }
        }
    }
}
